sudo: required
_aliases:
  - &ui-tests
    addons:
      firefox: latest-nightly
    apt:
      packages:
        - jwm
    env: TOXENV=discopane-ui-tests DISPLAY=:99.0 GECKODRIVER=0.19.1
    before_install:
      - wget -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER/geckodriver-v$GECKODRIVER-linux64.tar.gz
      - mkdir $HOME/geckodriver && tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
      - export PATH=$HOME/geckodriver:$PATH
      - firefox --version
      - geckodriver --version
    before_script:
      - sh -e /etc/init.d/xvfb start
      - sleep 5
      - jwm &
      - sleep 5
      - yarn start-func-test-server
    script: tox
  - &node6
    addons:
      firefox: latest
    language: node_js
    node_js: '6'
    before_install: npm install -g yarn
  - &node8
    addons:
      firefox: latest
    language: node_js
    node_js: '8'
    before_install: npm install -g yarn
services:
  - docker
cache:
  yarn: true
  directories:
  - node_modules
jobs:
  include:
    - stage:
      language: python
      python: 3.6
      <<: *ui-tests
      install: nvm install 6
    - stage:
      language: python
      python: 3.6
      <<: *ui-tests
      install: nvm install 8
    - stage:
      language: python
      python: 3.6
      env: TOXENV=flake8
      install: tox
      script: tox
    - stage:
      language: python
      python: 3.6
      env: TOXENV=dennis-lint
      install: tox
      script: tox
    - stage:
      <<: *node6
      env: TASK=build ADDONS_FRONTEND_BUILD_ALL=1
      script: yarn $TASK
    - stage:
      <<: *node6
      env: TASK=lint
      script: yarn $TASK
    - stage:
      <<: *node6
      env: TASK=test-ci
      script: yarn $TASK
    - stage:
      <<: *node6
      env: TASK=nsp-check
      script: yarn $TASK
    - stage:
      <<: *node8
      env: TASK=build ADDONS_FRONTEND_BUILD_ALL=1
      script: yarn $TASK
    - stage:
      <<: *node8
      env: TASK=lint
      script: yarn $TASK
    - stage:
      <<: *node8
      env: TASK=test-ci
      script: yarn $TASK
    - stage:
      <<: *node8
      env: TASK=nsp-check
      script: yarn $TASK
